Algoritmo "meu primeiro algoritmo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rogerio
// Data atual  : 11/05/2020
Var
// Seção de Declarações das variáveis 
   Nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Nota <- 100
   Escreva("Resultado:", nota)
Fimalgoritmo