Algoritmo "Olá Mundo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Cleison Melo
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rogerio
// Data atual  : 11/05/2020
Var
// Seção de Declarações das variáveis 
    NOME: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     Nome <- "Olá Mundo"
     Escreva (Nome)
Fimalgoritmo